### ISSUE TITLE
"auth token must be set" even i set it

### ISSUE THREAD

**Issue by KebabLord** [mopidy/mopidy-soundcloud#105]
I already set the auth token to the both config files:
/root/.config/mopidy/mopidy.conf
/etc/mopidy/mopidy.conf

running mopidyctl config returns:
```
[soundcloud]
enabled = true
explore_songs = 24
auth_token = ********
```
and seems it's set, however running mopidy config returns:
```
[soundcloud]
enabled = false  ; Extension disabled due to config errors.
explore_songs = 25
auth_token =   ; Must be set.
```
How can I set my auth_token correctly?

**Comment by kingosticks** [comment]
`mopidyctl` is for interacting with Mopidy running as a service and has nothing to do with the root user's config file at /root/.config/mopidy/mopidy.conf. Please take a look at https://docs.mopidy.com/en/latest/service/.

**Comment by KebabLord** [comment]
well, I already edited the config in  `/etc/mopidy/mopidy.conf` but i didn't help

**Comment by kingosticks** [comment]
How are you planning to run Mopidy. As your user (and is that really the `root` user?) or as a service? If it's as a service then it sound like your config is ready to go.

**Comment by KebabLord** [comment]
I'm a Kali user, I'm always root. I just want to use mopidy-soundcloud extension, dunno if as a service, I'm just running it through bash with basic "mopidy" command.

**Comment by kingosticks** [comment]
Then forget about /etc/mopidy/mopidy.conf and forget about `mopidyctl`, like the link I posted says. When you start Mopidy from your bash shell it'll print out:
> INFO     Loading config from `SOMEWHERE.conf`

That `SOMEWHERE.conf` file must have the `auth_token` set. Please check it does.

**Comment by KebabLord** [comment]
that's why I opened this ticket, I don't know where it is ;_;

**Comment by kingosticks** [comment]
It literally prints out the file location. Can you just provide the entire output you get in your console after starting mopidy.
