### ISSUE TITLE
SoundCloud app registration

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-soundcloud#110]
Hi @dz0ny!

We're updating the Mopidy website and how the authentication workflows work. While doing that, we discovered that we didn't have access to reconfigure the SoundCloud side of the OAuth setup.

Do you have access to the Mopidy app at https://soundcloud.com/you/apps ?

If so, is it possible to give us access to the Mopidy app registration too?

My SoundCloud username is "jodal". I'm assuming that @adamcik's username is "adamcik"?

**Comment by adamcik** [comment]
Looking at my own testing app I have registered I doubt we can do anything, other than confirm that Janez has the app under his control. For my own one I stuck with the callback being `http://localhost/soundcloud/callback` for instance...

**Comment by kingosticks** [comment]
Sadly, no answer.
