### ISSUE TITLE
Getting daily rate limite exceeded, have not played from SC at all today/yesterday

### ISSUE THREAD

**Issue by Drizzt321** [mopidy/mopidy-soundcloud#127]
So I'm using v3.0.1, and I've run into occasional problems where it's been a few days or longer since I used Mopidy to place SC tracks, or even looked at the Stream or what not. Yet, when I go to play some streams right now, I can view my Stream, view the new tracks that have shown up, but when I try and play it says daily rate limit exceeded. 

Does Mopidy-SoundCloud regularly ping out to SC behind the scenes or something, which is could cause the issue? Doesn't seem likely/possible, with a 15K requests per 24 hours. Especially if I'm not actually using it. 

Is there a debug logging I could turn on, to see what the extension is doing behind the scenes?

**Comment by kingosticks** [comment]
Unfortunately the rate limit is across everyone using our client ID. It's a stupid implementation by soundcloud and they show no signs of fixing it.

**Comment by Drizzt321** [comment]
@kingosticks Ohhh....I thought it was per API Token, not per Application. 

And I'd have to get my own Application ID in order to get my own, personal allotment of 15K?

**Comment by kingosticks** [comment]
Yes, except they closed new signups years ago!

However, turns out I spoke too soon and they are showing signs of fixing some of this finally. https://developers.soundcloud.com/blog/security-updates-api

**Comment by Drizzt321** [comment]
I can handle putting up my own auth endpoint (annoying), but it's that they closed the signups. In other words...no competition for their own apps! *sigh* :(
