### ISSUE TITLE
soundcloud plugin is not working

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-soundcloud#28]
@VeryStrangeMan reported the following in https://github.com/mopidy/mopidy/issues/768

> SoundCloud plugin, installed from apt.mopidy.com is not working and can't be enabled. > Maybe, it need to be updated?
> 
> Output of service mopidy run config: http://pastebin.com/Nk9Rsi1f, pay attention for last string: Extension disabled by self check.
> mopidy.conf: http://pastebin.com/ALhk6FN8
> extensions.d/soundcloud.conf: http://pastebin.com/bUg191Gs

**Comment by NellyWhadsDev** [comment]
Having the same issue as the OP.

I've tried the solutions outlines here and have found that the pip install method has no effect on mopidy at all anymore (the extension is not found in the first place) and installing through apt results in the OP's error.

I am running mopidy from it's own user (as a system service)

Can anyone point me in the right direction? My config file and mopidyctl config outputs are almost identical to the OP (some of the extensions are different)

**Comment by chroeseler** [comment]
NellyWhadsDev can you tell me which dependencies? After upgrading pacman and with that cleaning out some packages Soundclouds stops working. So I think thats the key. But I dont seem to find the right package...

Vg
