### ISSUE TITLE
Host authenticate page with Mopidy's webserver

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-soundcloud#32]
With the new web extension support, we should be able to move http://www.mopidy.com/authenticate to be a part of the Mopidy-SoundCloud extension, hosted on Mopidy's own web server.

You'd of course need to use `window.location` as part of the `redirect_uri` that is passed to SoundCloud, instead of `http://www.mopidy.com/soundcloud_callback`.

**Comment by jodal** [comment]
Any regular user would much rather authenticate on https://www.mopidy.com/authenticate than registering their own app to do it on http://localhost:6680/something. If the user trusts our code to run on their system, they should be able to trust that the authenticate code on www.mopidy.com doesn't send their SoundCloud token off to some server.

Closing as unfeasible/not interesting.

**Comment by dz0ny** [comment]
They can also override client_id in settings and generate client_secret via SoundCoud page.
