### ISSUE TITLE
Error when searching text has accented chars.

### ISSUE THREAD

**Issue by lfcipriani** [mopidy/mopidy-soundcloud#42]
The stacktrace I got is: 

Query: "vem chegando o verão"

Server returned error: { message: 'Application error',
  code: 0,
  data:
   { message: 'u\'\\xe3\'',
     traceback: 'Traceback (most recent call last):\n  File "/opt/twitter/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 130, in _handle_single_request\n    result = self._unwrap_result(result)\n  File "/opt/twitter/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 219, in _unwrap_result\n    result = result.get()\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/future.py", line 299, in get\n    exec(\'raise exc_info[0], exc_info[1], exc_info[2]\')\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop\n    response = self._handle_receive(message)\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive\n    return callee(*message[\'args\'], message[\'kwargs\'])\n  File "/opt/twitter/lib/python2.7/site-packages/mopidy/core/library.py", line 195, in search\n    return [result for result in pykka.get_all(futures) if result]\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/future.py", line 330, in get_all\n    return [future.get(timeout=timeout) for future in futures]\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/future.py", line 299, in get\n    exec(\'raise exc_info[0], exc_info[1], exc_info[2]\')\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop\n    response = self._handle_receive(message)\n  File "/opt/twitter/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive\n    return callee(*message[\'args\'], message[\'kwargs\'])\n  

File "/opt/twitter/lib/python2.7/site-packages/mopidy_soundcloud/library.py", line 177, in search\n    tracks=self.backend.remote.search(search_query)\n  
File "/opt/twitter/lib/python2.7/site-packages/mopidy_soundcloud/soundcloud.py", line 212, in search\n    quote_plus(query)\n

File "/opt/twitter/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1293, in quote_plus\n    s = quote(s, safe + \' \')\n  File "/opt/twitter/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1288, in quote\n    return \'\'.join(map(quoter, s))\nKeyError: u\'\\xe3\'\n',
     type: 'KeyError' } }

**Comment by jodal** [comment]
This was fixed by PR #55.

In related news, with the upcoming Mopidy 1.1, broken search in a single backend should no longer break search for other backends.
