### ISSUE TITLE
Config the token via API or WebSocket

### ISSUE THREAD

**Issue by alexsalas** [mopidy/mopidy-soundcloud#46]
Add the authentication token to the mopidy.conf config file from API or WebSocket

[soundcloud]
auth_token = 1-1111-1111111
explore_songs = 25

**Comment by jodal** [comment]
I think this is covered by mopidy/mopidy#367 and probably other issues there as well. Anyway, this is something that must be solved generally in mopidy/mopidy and nothing can be done in mopidy-soundcloud at this point in time.
