### ISSUE TITLE
Mopidy v1.0.1-1 (4/24): distorted music with extension

### ISSUE THREAD

**Issue by jakehemmerle** [mopidy/mopidy-soundcloud#51]
Hello,

Just updated mopidy today, and I noticed that the SoundCloud extension has lots of distortion when playing songs from SoundCloud.

What can I do to help?

**Comment by jakehemmerle** [comment]
Fixed with Mopidy 1.0.2 update.

**Comment by jodal** [comment]
Great! :-)
