### ISSUE TITLE
Authentication Token

### ISSUE THREAD

**Issue by Veltridze** [mopidy/mopidy-soundcloud#56]
When using the mopidy site I am unable to get an authentication token and am given the error 'Error: 401 - Unauthorized'

**Comment by adamcik** [comment]
I just tried reproducing this using both the spotify and soundcloud token setups and can't seem to get the error. Could it be you are blocking third party cookies or something else going wrong on your end?

Perhaps you could look at the developer mode in your browser to get some more info, as currently there is no way for us to get anywhere with this :(

**Comment by adamcik** [comment]
This seems to be a safari issue, and we are looking into it at the europython sprints as we have someone here who can reproduce.

**Comment by elsurudo** [comment]
Same issue here. Get the above error in Safari, but in Chrome and Firefox, the auth window simply disappears when I connect. The auth token is never shown

**Comment by elsurudo** [comment]
Nevermind, it did indeed work in Chrome :) I just didn't notice the token embedded in the page.

**Comment by adamcik** [comment]
Closing as this is stale by now.
