### ISSUE TITLE
Users are displayed with '+' instead of space

### ISSUE THREAD

**Issue by a1ex4** [mopidy/mopidy-soundcloud#64]
Every users (from Following for example) have a + sign instead of a blank space.

**Comment by jodal** [comment]
Sounds like the user name/title needs to be URI-decoded before being used.

**Comment by dreamlayers** [comment]
I don't understand why is urllib quote_plus() used on names of folders, via calling safe_url() in new_folder(). As expected, it doesn't only put in plus signs; it also uses percent encoding, with `Blank & Jones` becoming `Blank+%26+Jones`. The `unicodedata.normalize("NFKD", uri).encode("ASCII", "ignore")` also seems wrong, converting non-ASCII characters to ASCII approximations, like `ć` becoming `c`. 

In new_folder(name, path) changing `name=safe_url(name)` to simply `name=name` works for me. Unicode artist names are displayed properly in mopidy-mobile web interface and mpc, and are accessible.

new_folder() : https://github.com/mopidy/mopidy-soundcloud/blob/310ef8a080c90db3a4f2f4ca3e8df0e644d68fd5/mopidy_soundcloud/library.py#L17

safe_url() : https://github.com/mopidy/mopidy-soundcloud/blob/310ef8a080c90db3a4f2f4ca3e8df0e644d68fd5/mopidy_soundcloud/soundcloud.py#L23

**Comment by jodal** [comment]
Fixed by #112.
