### ISSUE TITLE
stuck at -->  INFO     Starting GLib mainloop

### ISSUE THREAD

**Issue by sanjay555** [mopidy/mopidy-soundcloud#77]
I am using Arch Linux, mopidy got stuck at  INFO     Starting GLib mainloop (in terminal)

**Comment by jodal** [comment]
Mopidy is probably ready for use at that point. Did you try connecting an MPD or HTTP client?

**Comment by jodal** [comment]
And how is this related to Mopidy-SoundCloud specifically?

**Comment by vorodevops** [comment]
@sanjay555 Can you check if the soundcloud extension is actually loaded?
In `/var/log/mopidy/mopidy.log` look for a line like this:
`2016-05-12 15:20:45,678 INFO [21869:MainThread] mopidy.__main__: Enabled extensions: *, soundcloud`
I had a similar issue on Debian/Steamos: No errors on the log but no soundcloud. Mopidy couldn't find the extension if it was installed with apt-get but it worked with pip. Something about paths.

**Comment by kingosticks** [comment]
I don't believe this can be related to Mopidy-Soundcloud.
