### ISSUE TITLE
Failed to lookup soundcloud song

### ISSUE THREAD

**Issue by kh0p** [mopidy/mopidy-soundcloud#78]
When I'm trying to get into "**Liked**" in my ncmpcpp client I'm getting this `INFO`:

```
INFO     Failed to lookup soundcloud:song/(yuxx bootleg demo).83080709: SoundCloud track not found
INFO     Failed to lookup soundcloud:song/YOU ARE INVITED.125240468: SoundCloud track not found
INFO     Failed to lookup soundcloud:song/Carving Ymir (old version).65413451: SoundCloud track not found
INFO     Failed to lookup soundcloud:song/Various YZYX Kawaii Loli Attack uMmr EdItIoN (Tracklist and Download in description).50694917: SoundCloud track not found
...
```

And so on. I think that Mopidy is running correctly. It prints:

```
INFO     New MPD connection from [::ffff:127.0.0.1]:54440
INFO     New MPD connection from [::ffff:127.0.0.1]:54444
INFO     New MPD connection from [::ffff:127.0.0.1]:54452
INFO     New MPD connection from [::ffff:127.0.0.1]:54456
...
```

I'm using Arch and I tried both `mopidy` official repo and `mopidy-git` [from AUR](https://aur.archlinux.org/packages/mopidy-soundcloud/). As far as I am concerned there is nothing wrong with my `modipy.config`. Is this some link-parsing error? 

Also I linked up AUR because maybe the problem lies in the PKGBUILD? Building is done by `python2 setup.py install --root="$pkgdir/" --optimize=1` command. And here is the list of dependencies:   
```PKGBUILD
depends=(
  'python2'
  'python2-requests'
  'python2-pykka>=1.1'
  'gstreamer0.10-ugly-plugins'
  'mopidy>=1.0'
)
```

**Comment by dz0ny** [comment]
Soundcloud is removing a lot of library, their free service will probably work until they rollout their pay option later this year. 

And those tracks were all removed from Soundcloud https://soundcloud.com/search?q=YZYX%20Kawaii%20Loli%20Attack%20uMmr%20EdItIoN

http://api.soundcloud.com/track/125240468?client_id=93e33e327fd8a9b77becd179652272e2
