### ISSUE TITLE
Add nixos to installation section

### ISSUE THREAD

**Issue by langston-barrett** [mopidy/mopidy-soundcloud#81]
NixOS also has a package for mopidy-soundcloud, called (perhaps unsurprisingly) mopidy-soundcloud.

**Comment by kingosticks** [comment]
If someone wants to create a PR of this - great.

**Comment by adamcik** [comment]
Installation instructions have been consolidated under https://mopidy.com/ext/soundcloud/ - if this still makes sense I would add it to the website under https://github.com/mopidy/website/tree/master/_ext
