### ISSUE TITLE
Liked asks for too much tracks

### ISSUE THREAD

**Issue by Pixdigit** [mopidy/mopidy-soundcloud#92]
When requesting liked tracks the limit of tracks is set to 10000. Not only does this take ages to request but also ultimately causes some part to fail. Sometimes its the client timing out. Sometimes soundcloud returns an internal server error…

**Comment by kingosticks** [comment]
Fixed generically in https://github.com/mopidy/mopidy-soundcloud/commit/168ee8f62b5dcc2784293019a96837516b7f613f. I don't know if we need this to be configurable on a per-endpoint basis. For example, show more liked tracks than search results. The config setting isn't ideally named and it needs to be documented in the README.
